default:
  path: /
  controller: HelloTestBundle\Controller\HelloTestController::helloTestAction

add_message:
  path: /add
  controller: HelloTestBundle\Controller\HelloTestController::addMessageAction