services:
  #FORM FORGE BUNDLE
  HelloTestBundle\Services\HelloTestManager:
    public: false
    arguments: ['@doctrine.orm.entity_manager', 'Hello Nas :p']

    test.hello.manager:
      alias: HelloTestBundle\Services\HelloTestManager
      public: true
#  test.hello.manager: ''